[package]
name = "turbo_fish"
version = "0.0.2"
authors = ["Vincent Combey <vcombey@student.42.fr>", "Mickael Billod <bmickael@student.42.fr>", "Sebastien Clolus <sclolus@student.42.fr>"]
edition = "2021"

[profile.release]
opt-level = 3
debug = false
panic = "abort"

[profile.dev]
panic = "abort"
debug = true

[lib]
crate-type = ["staticlib"]

[dependencies]
bit_field = "0.10.2"
bitflags = "2.3.2"
lock_api = "0.4.10"
derive_is_enum_variant = "0.1.1"
try_clone_derive = "0.1.1"
io = { path = "dependencies/io" }
mbr = { path = "dependencies/mbr" }
raw_data = { path = "dependencies/raw_data" }
const_assert = { path = "dependencies/const_assert" }
ext2 = { path = "dependencies/ext2" }
terminal = { path = "dependencies/terminal" }
i386 = { path = "dependencies/i386" }
sync = { path = "dependencies/sync" }
elf_loader = { path = "dependencies/elf_loader" }
messaging = { path = "dependencies/messaging" }
libc_binding = { path = "dependencies/libc_binding" }
kernel_modules = { path = "dependencies/kernel_modules" }
irq = { path = "dependencies/irq" }
interrupts = { path = "dependencies/interrupts" }
time = { path = "dependencies/time" }
ansi_escape_code = { path = "dependencies/ansi_escape_code" }
rtc_toolkit = { path = "dependencies/rtc_toolkit" }
screen = { path = "dependencies/screen" }

[dependencies.log]
version = "0.4.19"

[dependencies.fallible_collections]
version = "0.4.8"
features = ["unstable"]

[dependencies.itertools]
version = "0.10.5"
default-features = false

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]

[dependencies.arrayvec]
version = "0.7.3"
default-features = false
# std = []
# array-sizes-33-128 = [true]
# array-sizes-129-255 = [true]

[dev-dependencies]
[features]
exit-on-panic = ["terminal/exit-on-panic"]
serial-eprintln = ["terminal/serial-eprintln", "screen/serial-eprintln"]
std-print = ["terminal/std-print", "ext2/std-print", "elf_loader/std-print"]
#test-succeed = []
#test-failed = []
test-sodo-allocator = []
test-vmalloc = []
test-kmalloc = []
native-test-hard-drive-read-pio = []
native-test-hard-drive-write-pio = []
native-test-hard-drive-read-udma = []
native-test-hard-drive-write-udma = []
native-test-hard-drive-read-bios = []
native-test-hard-drive-write-bios = []
native-test-libc = []
test = []
no-exit-qemu = []
with-login = []

[workspace]
resolver = "2"
members = [
"dependencies/io",
"dependencies/mbr",
"dependencies/raw_data",
"dependencies/const_assert",
"dependencies/ext2",
"dependencies/terminal",
"dependencies/i386",
"dependencies/sync",
"dependencies/elf_loader",
"dependencies/messaging",
"dependencies/libc_binding",
"dependencies/kernel_modules",
"dependencies/irq",
"dependencies/interrupts",
"dependencies/time",
"dependencies/ansi_escape_code",
"dependencies/rtc_toolkit",
"dependencies/screen",
]
exclude = ["autobuild/nm_map_gen_rust", "integration_tester"]
