[package]
name = "elf_loader"
version = "0.1.0"
authors = ["vcombey <vcombey@student.42.fr>"]
edition = "2021"

[dependencies]
bitflags = "2.3.2"
terminal = { path = "../terminal" }

[features]
test = []
std-print = []
