[package]
name = "irq"
version = "0.1.0"
authors = ["mordak <bmickael@student.42.fr>"]
edition = "2021"
license = "GPL3"
description = "A small briefing about irq"
documentation = "cargo doc --open"
homepage = "index.html"

[dependencies]
io = { path = "../io" }