[package]
name = "integration_tester"
version = "0.1.0"
authors = ["vcombey <vcombey@student.42.fr>"]
edition = "2021"

[dependencies]
toml = "0.7.4"
wait-timeout = "0.2.0"
getopts = "0.2.21"
colored = "2.0.0"
